### ISSUE TITLE
Unable to pull, getting error.

### ISSUE THREAD

**Issue by Deepu2002d** [piyushgoyal1620/HacktoberFest2020#17]
Sir , I am new don't know much. Help me. I also want to add value to the files in this repository but getting an error while using git push - 
remote: Permission to piyushgoyal1620/HacktoberFest2020.git denied to Deepu2002d.
fatal: unable to access 'https://github.com/piyushgoyal1620/HacktoberFest2020/': The requested URL returned error: 403
What should I do?  

I was proposing some changes in the Temperature Converter.py. It would be good if we can convert the temperature units via CLI. And some other things were also in my mind.

Edit - No problem sir, I did it. Now, I know I first have to fork the repository.

**Comment by Deepu2002d** [comment]
This repo was eligible for hacktoberfest. Am I right? Than what's going on now.
Sir, I need help.

**Comment by Deepu2002d** [comment]
This repo was eligible for hacktoberfest. Am I right? Than what's going on now.
Sir accept my PR.
Sir, I need help.

**Comment by piyushgoyal1620** [comment]
Good Luck !!!

**Comment by Deepu2002d** [comment]
Please label my PR as hacktoberfest-accepted.
